apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: airflow-local

# We import the "No-Build" config from the remote repo
requires:
    - path: skaffold-remote-dev.yaml  # Point to the specific dev file

# NO BUILD SECTION! 
# We rely entirely on the pre-built image + mounts.